services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=${APP_REDIS_HOST}
      - REDIS_PORT=${APP_REDIS_PORT}
      - RABBITMQ_HOST=${APP_REBBITMQ_HOST}
      - RABBITMQ_PORT=${APP_REBBITMQ_PORT}

  rabbitmq:
    image: "rabbitmq:latest"
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data: